platform :ios, '7.0'

pod 'AFNetworking','~> 2.6.0'
#pod 'FMDB'
pod 'Masonry', '~> 0.6.2'
pod 'SDWebImage', '~> 3.7.3'
#pod 'MBProgressHud'
#pod 'SIAlertView'
pod 'MJRefresh', '~> 2.4.7'

# Github page: https://github.com/steipete/Aspects
pod 'Aspects','~>1.4.1'